log:
  level: info
plugins:
- args:
    concurrent: 2
    upstreams:
    - addr: udp://223.5.5.5:53
      enable_pipeline: true
    - addr: udp://119.29.29.29:53
      enable_pipeline: true
  tag: forward_local
  type: forward
- args:
    entry: forward_local
    listen: 127.0.0.1:5354
  tag: udp_server
  type: udp_server
- args:
    entry: forward_local
    listen: 127.0.0.1:5354
  tag: tcp_server
  type: tcp_server
